export const MESSAGE_ERRORS = {
  INVALID_CONTACT_ID: 'INVALID_CONTACT_ID',
  MESSAGE_ALREADY_IN_PROCESS_OF_SENDING:
    'MESSAGE_ALREADY_IN_PROCESS_OF_SENDING',
  MESSAGE_ALREADY_SENT: 'MESSAGE_ALREADY_SENT',
}
