export const MESSAGE_ERRORS = {
  INVALID_CONTACT_ID: 'INVALID_CONTACT_ID',
  MESSAGE_ALREADY_IN_PROCESS_OF_SENDING:
    'MESSAGE_ALREADY_IN_PROCESS_OF_SENDING',
  MESSAGE_ALREADY_SENT: 'MESSAGE_ALREADY_SENT',
  HOST_NOT_FOUND: 'HOST_NOT_FOUND',
  INVALID_ID: 'INVALID_ID',
  MESSAGE_NOT_SENT: 'MESSAGE_NOT_SENT',
}
