export enum VALIDATION_MESSAGE_ERROR {
  INVALID_CONTACT_ID = 'INVALID_CONTACT_ID',
  MEDIA_TYPE_NOT_ALLOWED = 'MEDIA_TYPE_NOT_ALLOWED',
  INVALID_URL = 'INVALID_URL',
  INVALID_FILENAME = 'INVALID_FILENAME',
  INVALID_PASS_ID = 'INVALID_PASS_ID',
}
